# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'camshare' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!
  #pod 'BoringSSL-GRPC'

  # Pods for camshare
	#pod 'camPod', :path => '/Users/jerasmus/Desktop/camshareFramework/camPod'
	pod 'camPod', :git => 'https://github.com/JancoDVTDev/camPod.git'

	pod 'Fabric', '~> 1.10.2'
	pod 'Crashlytics', '~> 3.14.0'
	pod 'Firebase/Performance'

  target 'camshareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'camshareUITests' do
    # Pods for testing
  end

end
