# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'camshare' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for camshare
	#pod 'camPod', :git => 'https://github.com/JancoDVTDev/camPod.git'
	pod 'camPod', :path => '/Users/jerasmus/Desktop/camshareFramework/camPod'

  target 'camshareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'camshareUITests' do
    # Pods for testing
  end

end
